---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hub-agent-auth-server
  labels:
    {{- include "hub-helm-chart.labels" . | nindent 4 }}
rules:
  - resources:
      - accesscontrolpolicies
    apiGroups:
      - hub.traefik.io
    verbs:
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - list
      - watch
